<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    protected $guarded = [];


    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->latest('updated_at');
        });
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    protected $casts = [
        'done' => 'boolean'
    ];
}
