<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Setting extends Model
{
    protected $table = 'settings';
    protected $guarded = [];
    public const DIR_IMAGE_UPLOADS = 'settings';
    public const URL = 'settings';
    public const currencies = [
        'USD' => 1,
        'AED' => 2,
        'SAR' => 3,
    ];


    protected static function boot()
    {
        parent::boot(); //  Change the autogenerated stub
        static::addGlobalScope('orderedBy', function (Builder $builder) {
            $builder->orderBy('ordered');
        });

        if (request()->is('api/*')) {
            static::addGlobalScope('notDraft', function (Builder $builder) {
                $builder->where('draft', false);
            });
        }

    }

    static public function getSettings()
    {
        $settings = Cache::remember('settings', 60, function () {
            return self::select('key', 'value')->get();
        });
        return $settings;
    }

    static public function getCurrency($val)
    {
        switch ($val) {
            case self::currencies['USD']:
                return [
//                    'ar' => 'دولار',
                    'ar' => 'USD',
                    'en' => 'USD',
//                    'en' => 'dollar',
                ];
            case self::currencies['AED']:
                return [
//                    'ar' => 'درهم',
                    'ar' => 'AED',
                    'en' => 'AED',
                ];
            case self::currencies['SAR']:
                return [
//                    'ar' => 'ريال',
                    'ar' => 'SAR',
                    'en' => 'SAR',
                ];
        }
    }
}
